---
- name: configure repository
  hosts: nodes
  vars:
    my_package: nmap
  tasks:
  - name: get package facts
    package_facts:
      manager: auto
  - name: show pacakge facts for my_package
    debug:
      var: ansible_facts.packages[my_package]
    when: my_package in ansible_facts.packages
  - name: connect to example repo
    yum_repository:
      name: lesson12
      description: RHCE8 lesson 12 repo
      file: lesson 12

NOT FINISHED: (4)
