---
- name: configure Apache storage configuration
  hosts: lamp
  vars_files:
    - vars/storage.yml
  tasks:
    - name: verify partition existence
      parted:
        device: /dev/sdb
        state: present
        number: "{{ item.number }}"
        part_start: "{{ item.start }}"
        part_end: "{{ item.end }}"
      loop: "{{ partitions }}"
    - name: verify VG existence
      lvg:
        vg: "{{ item.name }}"
        pvs: "{{ item.devices }}"
      loop: "{{ vgs }}"
    - name: create LVs if needed
      lvol:
        vg: "{{ item.vgroup }}"
        lv: "{{ item.name }}"
        size: "{{ item.size }}"
      loop: "{{ lvs }}"
      when: item.name not in ansible_lvm["lvs"]
    - name: verify XFS filesystem on each LV
      debug: 
        msg: TODO
      loop: "{{ lvs }}"
    - name: mount LVs
      debug:
        msg: TODO
      loop: "{{ lvs }}"

