---
- name: sample of stat and assert
  hosts: all
  tasks:
  - name: stat a directory
    stat:
      path: /etc/hosts
    register: sta
  - name: assert that /etc is a directory
    assert:
      that: sta.stat.isdir
