---
- name: install httpd
  hosts: ansible2.example.com
  tasks:
    - name: install package
      package:
        name: httpd
        state: present
    - name: create an index.html
      copy:
        content: 'welcome to this webserver'
        dest: /var/www/html/index.html
    - name: start the service
      service: 
        name: httpd
        state: started
        enabled: true
    - name: open firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
